apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 
  description: 
  tags:
    - 
  links:
    - title: Website
      url: http://harness.io
  annotations:
    github.com/project-slug: harnessworkshop/idp-workshop
    backstage.io/techdocs-ref: dir:../
    lighthouse.com/website-url: https://harness.io
spec:
  type: service
  owner: 
  lifecycle: experimental
  consumesApis:
    - spotify
  providesApis:
    - petstore
  dependsOn:
    - 
